name: base_app
description: Base Module
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  get_storage: ^2.0.2
  dio: ^4.0.6
  logger: any
  json_annotation: ^4.5.0
  intl: ^0.17.0
  cached_network_image: ^3.2.0
  flutter_svg: ^1.0.3
  pull_to_refresh: ^2.0.0
  enum_to_string: ^2.0.1
  flutter_easyloading: ^3.0.5
  validators: ^3.0.0
  package_info_plus: ^1.4.2
  cupertino_icons: ^1.0.5
  floor: ^1.2.0
  flutter_secure_storage: ^5.0.2
  shimmer: ^2.0.0
  shared_preferences: ^2.0.15
  datadog_flutter_plugin: ^1.0.0-rc.1
  datadog_tracking_http_client: ^1.1.0-rc.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  floor_generator: any
  json_serializable: any
  analyzer: any

flutter:
  uses-material-design: true
